### ISSUE TITLE
4 qbit susbsytems of an 8 qbit system

### ISSUE THREAD

**Issue by jacksonhenry3** [jacksonhenry3/Qnibble#1]
Hi @UnnatiAkhouri ,

This is an "issue" a way to track problems and questions about the code. I like to use it as a way to write down questions so we have a record of them. It just lets me not have to remember as much, so they might be directed at me in the future. I'll tag you if they are directed at you, but feel free to ignore them if you don't want to take a look. I'll reference them at our meetings, like notes.

in 8-qubits model (1).nb you ralk about the two configurations
![image](https://user-images.githubusercontent.com/1857496/141042001-7b345a09-989e-456f-863b-3da1a9745f86.png)
as though that were all the possibilities. Is that what you meant? if so, why can't we include, for example the top four in a line and the bottom four in a line and many others? e.g.
![image](https://user-images.githubusercontent.com/1857496/141042356-1ae0e9d7-0e01-4f9c-9a1a-101d12c952bc.png)

**Comment by UnnatiAkhouri** [comment]
I don't know how to respond on github so I will respond here for now. Also I can't see the images that you've linked but I am going to assume its just the groupings of the qubits.

So, I chose the qubits that way because i wanted to track a particular qubit as the temperature qubit in the groupings and a particular qubit as the gradient qubit. Then, only such groupings ensured that. We do not have to retain this in the larger model because we will be averaging the temperature anyway.
Sorry, yesterday was my GR day so I didn't respond earlier.

Additionally, there is a series of talk coming up for today at tomorrow between 2-3:30 which is given by the funding group Sarah is part of for this (and some other qubit projects) projects. It could be interesting to attend these if you want to see how this type of research fits in. I will be attending them and can share the summary as well!

Here is the link in case you'd like to attend - Zoom link: https://brandeis.zoom.us/j/92349888981

Thanks!
Warm regards,
Unnati
________________________________
From: Jackson Henry ***@***.***>
Sent: 09 November 2021 22:10
To: jacksonhenry3/Qnibble ***@***.***>
Cc: Akhouri, Unnati ***@***.***>; Assign ***@***.***>
Subject: [jacksonhenry3/Qnibble] 4 qbit susbsytems of an 8 qbit system (Issue #1)


Hi @UnnatiAkhouri<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUnnatiAkhouri&data=04%7C01%7Cuja5020%40psu.edu%7C1c4e0f808bfe4e4f8a8208d9a3f7a8f4%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637721106372263439%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Riu9goBLHRVfp5xv%2F0u75vdWUSC%2B%2BrsEyOQdvTNRyZo%3D&reserved=0> ,

This is an "issue" a way to track problems and questions about the code. I like to use it as a way to write down questions so we have a record of them. It just lets me not have to remember as much, so they might be directed at me in the future. I'll tag you if they are directed at you, but feel free to ignore them if you don't want to take a look. I'll reference them at our meetings, like notes.

in 8-qubits model (1).nb you ralk about the two configurations
[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1857496%2F141042001-7b345a09-989e-456f-863b-3da1a9745f86.png&data=04%7C01%7Cuja5020%40psu.edu%7C1c4e0f808bfe4e4f8a8208d9a3f7a8f4%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637721106372273433%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mIBo4KfyAwD9V7aD%2FMdte2F%2BmIXBK1ZFPuDr3WBUJWI%3D&reserved=0>
as though that were all the possibilities. Is that what you meant? if so, why can't we include, for example the top four in a line and the bottom four in a line and many others? e.g.
[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1857496%2F141042356-1ae0e9d7-0e01-4f9c-9a1a-101d12c952bc.png&data=04%7C01%7Cuja5020%40psu.edu%7C1c4e0f808bfe4e4f8a8208d9a3f7a8f4%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637721106372273433%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FpKaw8iXBT5%2BUgpdRiIGy%2BjVdAjOWrA4NkVYMbzFt0o%3D&reserved=0>

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjacksonhenry3%2FQnibble%2Fissues%2F1&data=04%7C01%7Cuja5020%40psu.edu%7C1c4e0f808bfe4e4f8a8208d9a3f7a8f4%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637721106372283433%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=c%2F7NKnyIHXUQFgiq0wzltuq2Q%2FgwwfWV7GwOhUM0r9c%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWNJKEE32QB34D366ITS3CDULHPCTANCNFSM5HW2MXGA&data=04%7C01%7Cuja5020%40psu.edu%7C1c4e0f808bfe4e4f8a8208d9a3f7a8f4%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637721106372283433%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gMNQBd3z%2BqxJxiXuy%2FMKb19X72%2FJJEnm%2BqX7JHShU20%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cuja5020%40psu.edu%7C1c4e0f808bfe4e4f8a8208d9a3f7a8f4%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637721106372293425%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nx%2BEPv5XIHHyjX815wpAM3RyK6E4cRTU%2BdJ1Z9JiblQ%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cuja5020%40psu.edu%7C1c4e0f808bfe4e4f8a8208d9a3f7a8f4%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637721106372293425%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2BLfX2ACo%2BS5rW5%2Ba5BP5Efs42QsreKFbnr43AwSU4s%3D&reserved=0>.
